### ISSUE TITLE
integrating to campskeleton

### ISSUE THREAD

**Issue by bnymnsntrk** [twak/jutils#5]
beginner here, how do i add utils to make campskeleton work? because pom file of campskeleton gives an error about org.twak.utils. thanks in advance.

**Comment by twak** [comment]
what environment are you using? an IDE (eclipse or intellj etc...) or command line?

**Comment by bnymnsntrk** [comment]
i'm using eclipse (photon)

**Comment by twak** [comment]
typically you would checkout jutils, and add it as a separate maven project in eclipse alongside campskeleton. If you then "enable workspace resolution" in m2e it should be picked up by campskeleton?

**Comment by bnymnsntrk** [comment]
ok i'll give it a try, thank you.

**Comment by bnymnsntrk** [comment]
works like a charm! problem solved, thanks again.
if anyone tries to do the same, right click on your project>maven>assign working sets and select utils.
